ALTER TABLE IF EXISTS admin_navigation_item
    ADD COLUMN IF NOT EXISTS required_role VARCHAR(20) DEFAULT 'USER' NOT NULL;

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS pg_provider VARCHAR(40) DEFAULT 'MOCK' NOT NULL;

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS approval_request_key VARCHAR(120);

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS product_name VARCHAR(200);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS pg_provider VARCHAR(40);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(40);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS tid VARCHAR(120);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(120);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS http_status INTEGER;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS success_yn BOOLEAN;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS error_message VARCHAR(300);

CREATE TABLE IF NOT EXISTS payment_recovery_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    task_key VARCHAR(160) NOT NULL,
    payment_id BIGINT,
    cancel_id BIGINT,
    order_no VARCHAR(80),
    tid VARCHAR(120),
    idempotency_key VARCHAR(120),
    recovery_type VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    retry_count INTEGER NOT NULL,
    max_retry_count INTEGER NOT NULL,
    last_error_message VARCHAR(300),
    last_tried_at TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT uk_payment_recovery_task_key UNIQUE (task_key)
);

CREATE TABLE IF NOT EXISTS alimtalk_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    payment_id BIGINT NOT NULL,
    sales_id BIGINT,
    message_key VARCHAR(120) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    retry_count INTEGER NOT NULL,
    max_retry_count INTEGER DEFAULT 5 NOT NULL,
    last_error_message VARCHAR(300),
    processing_started_at TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT uk_alimtalk_queue_message_key UNIQUE (message_key)
);

ALTER TABLE IF EXISTS external_send_request
    ADD COLUMN IF NOT EXISTS max_retry_count INTEGER DEFAULT 5 NOT NULL;

ALTER TABLE IF EXISTS external_send_request
    ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMP;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS payment_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS cancel_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS original_sales_transaction_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS pg_transaction_id VARCHAR(120);

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS supply_amount NUMERIC(19, 2) DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(19, 2) DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS ledger_status VARCHAR(30) DEFAULT 'POSTED' NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS settlement_status VARCHAR(30) DEFAULT 'NOT_SETTLED' NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS pg_code VARCHAR(40);

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(40);

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS seller_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS order_item_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS confirmed_yn BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP;

-- confirmed_yn 도입 이전에 정산까지 처리된 과거 매출은 확정된 것으로 간주한다(미확정 매출 목록 오염 방지).
UPDATE sales_transaction SET confirmed_yn = TRUE, confirmed_at = COALESCE(confirmed_at, occurred_at)
    WHERE confirmed_yn = FALSE AND settlement_included_yn = TRUE;

UPDATE sales_transaction
SET pg_transaction_id = tid
WHERE pg_transaction_id IS NULL;

UPDATE sales_transaction
SET total_amount = sale_amount
WHERE total_amount = 0;

UPDATE sales_transaction
SET supply_amount = ROUND(total_amount * 10 / 11, 0),
    vat_amount = total_amount - ROUND(total_amount * 10 / 11, 0)
WHERE supply_amount = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_approval_key_idx
    ON payment_transaction (approval_request_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_order_no_idx
    ON payment_transaction (order_no);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_tid_idx
    ON payment_transaction (tid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_cancel_request_key_idx
    ON payment_cancel (cancel_request_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sales_transaction_source_idx
    ON sales_transaction (source_type, source_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_external_send_request_key_idx
    ON external_send_request (request_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_alimtalk_queue_message_key_idx
    ON alimtalk_queue (message_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_recovery_task_key_idx
    ON payment_recovery_task (task_key);

ALTER TABLE IF EXISTS commerce_order ADD COLUMN IF NOT EXISTS paid_amount DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS commerce_order ADD COLUMN IF NOT EXISTS cancelled_amount DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS commerce_order ADD COLUMN IF NOT EXISTS stock_restored BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS option_summary VARCHAR(500);
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS option_additional_amount DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS selected_option_value_ids VARCHAR(500);
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS addon_item BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS product_variant_id BIGINT;
ALTER TABLE IF EXISTS commerce_order ADD COLUMN IF NOT EXISTS purchase_confirmed_at TIMESTAMP;
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(19,2);
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS cost_of_goods_sold DECIMAL(19,2);
ALTER TABLE IF EXISTS commerce_order_item ADD COLUMN IF NOT EXISTS category_name VARCHAR(100);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS inventory_managed BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS product_option_group (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, group_name VARCHAR(100) NOT NULL, selection_type VARCHAR(20) NOT NULL, required_option BOOLEAN NOT NULL, min_selection INT NOT NULL, max_selection INT NOT NULL, sort_order INT NOT NULL, exposed BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS product_option_value (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, option_group_id BIGINT NOT NULL, value_name VARCHAR(100) NOT NULL, additional_price DECIMAL(19,2) NOT NULL, inventory_managed BOOLEAN NOT NULL, stock_quantity INT NOT NULL, sale_status VARCHAR(30) NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS option_group_template (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, template_name VARCHAR(100) NOT NULL, selection_type VARCHAR(20) NOT NULL, required_option BOOLEAN NOT NULL, min_selection INT NOT NULL, max_selection INT NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS option_value_template (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, template_group_id BIGINT NOT NULL, value_name VARCHAR(100) NOT NULL, default_additional_price DECIMAL(19,2) NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS product_addon_group (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, group_name VARCHAR(100) NOT NULL, min_quantity INT NOT NULL, max_quantity INT NOT NULL, sort_order INT NOT NULL, exposed BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS product_addon_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, addon_group_id BIGINT NOT NULL, addon_product_id BIGINT NOT NULL, max_quantity INT NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT uk_addon_group_product UNIQUE(addon_group_id, addon_product_id));
CREATE TABLE IF NOT EXISTS product_variant (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, sku VARCHAR(100) NOT NULL, combination_key VARCHAR(500) NOT NULL, option_summary VARCHAR(500) NOT NULL, additional_price DECIMAL(19,2) NOT NULL, stock_quantity INT NOT NULL, sale_status VARCHAR(30) NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT uk_product_variant_sku UNIQUE(sku), CONSTRAINT uk_product_variant_combination UNIQUE(product_id, combination_key));

-- 구버전 로컬 DB는 category_name 하나만 UNIQUE라 매장별 동일 카테고리를 저장할 수 없다.
-- 현재 엔티티의 (store_code, category_name) 제약조건으로 교체되도록 이전 제약을 먼저 제거한다.
ALTER TABLE IF EXISTS product_category DROP CONSTRAINT IF EXISTS uk_product_category_name;
ALTER TABLE IF EXISTS product DROP CONSTRAINT IF EXISTS uk_product_code;
