server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:yeni_portfolio;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/data-fly.sql
      encoding: UTF-8
      continue-on-error: false

logging:
  level:
    root: info