package com.yeni.backoffice.core.payment.service;
import com.yeni.backoffice.core.payment.dto.PgReconciliationDtos.*;import com.yeni.backoffice.core.payment.entity.*;import com.yeni.backoffice.core.payment.enums.*;import com.yeni.backoffice.core.payment.repository.*;import com.yeni.backoffice.core.common.exception.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;
@Service public class PgSettlementReconciliationService{
 private final PgSettlementImportRepository imports;private final PgSettlementReconciliationRepository rows;private final SalesTransactionRepository sales;private final AuditLogRepository audits;
 public PgSettlementReconciliationService(PgSettlementImportRepository i,PgSettlementReconciliationRepository r,SalesTransactionRepository s,AuditLogRepository a){imports=i;rows=r;sales=s;audits=a;}
 @Transactional public ImportResponse importCsv(String fileName,String pgCompany,String mid,LocalDate businessDate,String csv){if(csv==null||csv.isBlank())throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"정산 파일이 비어 있습니다.");LocalDateTime importedAt=LocalDateTime.now();PgSettlementImport batch=imports.save(PgSettlementImport.builder().fileName(fileName).pgCompany(pgCompany).mid(mid).businessDate(businessDate).totalCount(0).matchedCount(0).mismatchCount(0).status("PROCESSING").build());Set<Long> matchedIds=new HashSet<>();LocalDateTime[] fileCutoff={null};int total=0,matched=0,mismatch=0;String[] lines=csv.replace("\r","").split("\n");for(int n=1;n<lines.length;n++){if(lines[n].isBlank())continue;String[] c=lines[n].split(",",-1);if(c.length<4)throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,(n+1)+"행 형식이 올바르지 않습니다. tid,orderNo,type,amount,fee 순서가 필요합니다.");String tid=c[0].trim(),orderNo=c[1].trim(),typeStr=c[2].trim().toUpperCase();BigDecimal pgAmount=money(c[3],n);BigDecimal fee=c.length>4&&!c[4].isBlank()?money(c[4],n):BigDecimal.ZERO;
// 같은 TID에 SALE·CANCEL 두 행이 있을 수 있으므로 type까지 맞춰 대사한다.
SaleType csvType=null;try{csvType=SaleType.valueOf(typeStr);}catch(Exception ignore){}
SalesTransaction internal=(csvType!=null?sales.findFirstByTidAndSaleTypeOrderByIdAsc(tid,csvType):Optional.<SalesTransaction>empty())
   .or(()->sales.findFirstByTidOrderByIdAsc(tid)).orElse(null);PgReconciliationStatus status;String reason;if(internal==null){status=PgReconciliationStatus.PG_ONLY;reason="PG 파일에만 존재하는 거래";}else if(internal.getTotalAmount().compareTo(pgAmount)!=0){status=PgReconciliationStatus.AMOUNT_MISMATCH;reason="내부 원장과 PG 승인 금액 불일치";matchedIds.add(internal.getId());}else{status=PgReconciliationStatus.MATCHED;reason="거래 및 금액 일치";matched++;matchedIds.add(internal.getId());}if(internal!=null&&internal.getOccurredAt()!=null&&(fileCutoff[0]==null||internal.getOccurredAt().isAfter(fileCutoff[0])))fileCutoff[0]=internal.getOccurredAt();if(status!=PgReconciliationStatus.MATCHED)mismatch++;rows.save(PgSettlementReconciliation.builder().importId(batch.getId()).salesTransactionId(internal==null?null:internal.getId()).tid(tid).orderNo(orderNo).internalAmount(internal==null?null:internal.getTotalAmount()).pgAmount(pgAmount).pgFee(fee).status(status).reason(reason).resolutionStatus(status==PgReconciliationStatus.MATCHED?PgReconciliationResolutionStatus.NOT_REQUIRED:PgReconciliationResolutionStatus.OPEN).build());total++;}
  for(SalesTransaction internal:sales.findByBusinessDateBetweenOrderByOccurredAtDesc(businessDate,businessDate)){if(!matchedIds.contains(internal.getId())){
   // 파일에 담긴 마지막 거래 시각(fileCutoff) 이후에 발생한 내부 거래(데모 중 즉석 테스트 주문 등)는
   // 불일치가 아니라 "이 파일 범위를 벗어난 — 다음 파일 대상" 거래다.
   LocalDateTime cutoff=fileCutoff[0]!=null?fileCutoff[0]:importedAt;
   boolean afterFile=internal.getOccurredAt()!=null&&internal.getOccurredAt().isAfter(cutoff);
   rows.save(PgSettlementReconciliation.builder().importId(batch.getId()).salesTransactionId(internal.getId()).tid(internal.getTid()).orderNo(internal.getOrderNo()).internalAmount(internal.getTotalAmount()).status(PgReconciliationStatus.INTERNAL_ONLY)
    .reason(afterFile?"PG 정산 파일 수신 이후 발생한 거래 — 다음 파일에서 대사됩니다.":"내부 원장에만 존재하는 거래")
    .resolutionStatus(afterFile?PgReconciliationResolutionStatus.NOT_REQUIRED:PgReconciliationResolutionStatus.OPEN).build());
   total++;if(!afterFile)mismatch++;}}
  batch.complete(total,matched,mismatch);return response(batch);}
 @Transactional(readOnly=true)public List<ImportResponse> list(){return imports.findAllByOrderByIdDesc().stream().map(this::response).toList();}
 @Transactional(readOnly=true)public ImportResponse get(Long id){return response(imports.findById(id).orElseThrow(()->new NotFoundException(ErrorCode.NOT_FOUND)));}
 @Transactional(readOnly=true) public String sampleCsv(LocalDate businessDate, boolean includeMismatch) {
  List<SalesTransaction> transactions=sales.findByBusinessDateBetweenOrderByOccurredAtDesc(businessDate,businessDate);
  if(transactions.isEmpty())throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"선택한 영업일에 샘플로 만들 매출 원장이 없습니다. 결제 시뮬레이션을 먼저 실행하거나 거래가 있는 날짜를 선택해 주세요.");
  StringBuilder csv=new StringBuilder("tid,orderNo,type,amount,fee\n");
  for(int index=0;index<transactions.size();index++){
   SalesTransaction transaction=transactions.get(index);BigDecimal amount=transaction.getTotalAmount();
   if(includeMismatch&&index==0)amount=amount.add(new BigDecimal("100"));
   BigDecimal fee=amount.multiply(new BigDecimal("0.033")).setScale(0,RoundingMode.HALF_UP);
   csv.append(transaction.getTid()).append(',').append(transaction.getOrderNo()).append(',').append(transaction.getSaleType().name()).append(',').append(amount.toPlainString()).append(',').append(fee.toPlainString()).append('\n');
  }
  if(includeMismatch)csv.append("TID-PG-ONLY-SAMPLE,ORDER-PG-ONLY-SAMPLE,SALE,15000,495\n");
  return csv.toString();
 }
 @Transactional public RowResponse updateResolution(Long rowId,ResolutionRequest request){PgSettlementReconciliation row=rows.findById(rowId).orElseThrow(()->new NotFoundException(ErrorCode.NOT_FOUND));PgReconciliationResolutionStatus target;try{target=PgReconciliationResolutionStatus.valueOf(request.status());}catch(Exception e){throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"지원하지 않는 처리 상태입니다.");}if(row.getStatus()==PgReconciliationStatus.MATCHED)throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"일치 거래는 예외 처리할 수 없습니다.");if(request.assignee()==null||request.assignee().isBlank())throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"담당자를 입력해 주세요.");if(request.note()==null||request.note().isBlank())throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"조치 메모를 입력해 주세요.");String before=row.getResolutionStatus().name()+" | "+Objects.toString(row.getAssignee(),"-")+" | "+Objects.toString(row.getResolutionNote(),"-");if(target==PgReconciliationResolutionStatus.IN_REVIEW)row.startReview(request.assignee().trim(),request.note().trim());else if(target==PgReconciliationResolutionStatus.RESOLVED||target==PgReconciliationResolutionStatus.EXCLUDED)row.resolve(target,request.assignee().trim(),request.note().trim());else throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,"확인 중, 해결, 제외 상태만 선택할 수 있습니다.");audits.save(AuditLog.builder().domainType("PG_RECONCILIATION").actionType("RESOLUTION_"+target.name()).referenceKey(String.valueOf(rowId)).description(request.note().trim()).actor(request.assignee().trim()).resultStatus("SUCCESS").beforeValue(before).afterValue(target.name()+" | "+request.assignee().trim()+" | "+request.note().trim()).loggedAt(LocalDateTime.now()).build());return rowResponse(row);}
 private ImportResponse response(PgSettlementImport b){List<RowResponse> detail=rows.findByImportIdOrderById(b.getId()).stream().map(this::rowResponse).toList();int unresolved=(int)detail.stream().filter(r->!List.of("NOT_REQUIRED","RESOLVED","EXCLUDED").contains(r.resolutionStatus())).count();return new ImportResponse(b.getId(),b.getFileName(),b.getPgCompany(),b.getMid(),b.getBusinessDate(),b.getTotalCount(),b.getMatchedCount(),b.getMismatchCount(),unresolved,b.getStatus(),b.getCreatedAt(),detail);}
 private RowResponse rowResponse(PgSettlementReconciliation r){List<ActionResponse> actions=audits.findByDomainTypeAndReferenceKeyOrderByLoggedAtDesc("PG_RECONCILIATION",String.valueOf(r.getId())).stream().map(a->new ActionResponse(a.getActionType(),a.getActor(),a.getBeforeValue(),a.getAfterValue(),a.getDescription(),a.getLoggedAt())).toList();return new RowResponse(r.getId(),r.getSalesTransactionId(),r.getTid(),r.getOrderNo(),r.getInternalAmount(),r.getPgAmount(),r.getPgFee(),r.getStatus().name(),r.getReason(),r.getResolutionStatus().name(),r.getAssignee(),r.getResolutionNote(),r.getResolvedAt(),actions);}
 private BigDecimal money(String value,int row){try{return new BigDecimal(value.trim());}catch(Exception e){throw new ValidationBusinessException(ErrorCode.VALIDATION_ERROR,(row+1)+"행 금액 형식이 올바르지 않습니다.");}}
}
