-- Baseline schema for PostgreSQL, generated from JPA entities (Hibernate PostgreSQLDialect).
-- 이후 스키마 변경은 V2, V3... 로 추가한다. 이 파일은 수정하지 않는다.
-- 프로젝트 관례상 DB 레벨 FK는 admin_navigation 외에는 두지 않고 애플리케이션이 무결성을 보장한다.

    create table admin_navigation_group (
        sort_order integer not null,
        use_yn boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        group_code varchar(255) not null unique,
        group_name varchar(255) not null,
        primary key (id)
    );

    create table admin_navigation_item (
        depth integer not null,
        display_yn boolean not null,
        is_deleted boolean not null,
        sort_order integer not null,
        use_yn boolean not null,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        navigation_group_id bigint not null,
        parent_navigation_item_id bigint,
        updated_at timestamp(6) not null,
        icon varchar(255),
        item_name varchar(255) not null,
        item_url varchar(255) not null,
        required_role varchar(255) not null check (required_role in ('USER','ADMIN')),
        primary key (id)
    );

    create table alimtalk_queue (
        max_retry_count integer not null,
        retry_count integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        payment_id bigint not null,
        processing_started_at timestamp(6),
        sales_id bigint,
        sent_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(30) not null check (status in ('READY','SENDING','SUCCESS','FAILED','RETRY_READY')),
        event_type varchar(40) not null,
        message_key varchar(120) not null,
        last_error_message varchar(300),
        primary key (id),
        constraint uk_alimtalk_queue_message_key unique (message_key)
    );

    create table audit_log (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logged_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        result_status varchar(30),
        action_type varchar(40) not null,
        domain_type varchar(40) not null,
        actor varchar(60),
        reference_key varchar(80),
        request_id varchar(80),
        after_value text,
        before_value text,
        description text,
        primary key (id)
    );

    create table chart_of_account (
        active boolean not null,
        sort_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        code varchar(10) not null,
        account_type varchar(20) not null check (account_type in ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
        name varchar(60) not null,
        primary key (id),
        constraint uk_chart_of_account_code unique (code)
    );

    create table commerce_brand (
        active boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        business_type varchar(30) not null check (business_type in ('FOOD_SERVICE','ONLINE_RETAIL')),
        brand_code varchar(40) not null,
        brand_name varchar(100) not null,
        primary key (id),
        constraint uk_commerce_brand_code unique (brand_code)
    );

    create table commerce_delivery (
        created_at timestamp(6) not null,
        delivered_at timestamp(6),
        id bigint generated by default as identity,
        order_id bigint not null,
        returned_at timestamp(6),
        shipped_at timestamp(6),
        updated_at timestamp(6) not null,
        zip_code varchar(10),
        status varchar(20) not null check (status in ('PREPARING','IN_TRANSIT','DELIVERED','RETURNED')),
        receiver_phone varchar(30) not null,
        carrier varchar(40),
        receiver_name varchar(60) not null,
        tracking_number varchar(60),
        address2 varchar(100),
        address1 varchar(200) not null,
        delivery_request varchar(200),
        return_reason varchar(200),
        primary key (id)
    );

    create table commerce_order (
        cancelled_amount numeric(19,2) not null,
        delivery_fee numeric(19,2) not null,
        discount_amount numeric(19,2) not null,
        paid_amount numeric(19,2) not null,
        payable_amount numeric(19,2) not null,
        product_amount numeric(19,2) not null,
        stock_restored boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        payment_id bigint,
        purchase_confirmed_at timestamp(6),
        store_id bigint,
        updated_at timestamp(6) not null,
        order_status varchar(30) not null check (order_status in ('PENDING_PAYMENT','CREATED','PAID','PURCHASE_CONFIRMED','PAYMENT_FAILED','PARTIALLY_CANCELLED','CANCELLED')),
        payment_status varchar(30) not null check (payment_status in ('READY','APPROVED','APPROVE_UNKNOWN','FAILED')),
        buyer_phone varchar(40),
        store_code varchar(40),
        buyer_name varchar(80) not null,
        order_no varchar(100) not null,
        store_name varchar(100),
        tid varchar(120),
        product_name varchar(160) not null,
        last_message varchar(200),
        primary key (id),
        constraint uk_commerce_order_no unique (order_no)
    );

    create table commerce_order_item (
        addon_item boolean not null,
        cost_of_goods_sold numeric(19,2),
        item_amount numeric(19,2) not null,
        option_additional_amount numeric(19,2) not null,
        quantity integer not null,
        shipped_yn boolean not null,
        unit_cost numeric(19,2),
        unit_price numeric(19,2) not null,
        created_at timestamp(6) not null,
        delivery_id bigint,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint,
        product_variant_id bigint,
        shipped_at timestamp(6),
        updated_at timestamp(6) not null,
        product_code varchar(80) not null,
        category_name varchar(100),
        option_name varchar(200),
        product_name varchar(200) not null,
        option_summary varchar(500),
        selected_option_value_ids varchar(500),
        primary key (id)
    );

    create table commerce_return (
        refund_amount numeric(19,2),
        return_shipping_fee numeric(19,2) not null,
        created_at timestamp(6) not null,
        delivery_id bigint,
        id bigint generated by default as identity,
        inspected_at timestamp(6),
        order_id bigint not null,
        processed_at timestamp(6),
        updated_at timestamp(6) not null,
        refund_status varchar(20) check (refund_status in ('NOT_REQUIRED','PENDING','SUCCESS','FAILED')),
        responsibility varchar(20) not null check (responsibility in ('CUSTOMER_FAULT','SELLER_FAULT')),
        status varchar(20) not null check (status in ('REQUESTED','INSPECTING','COMPLETED','REJECTED')),
        reason varchar(500) not null,
        refund_failure_reason varchar(500),
        reject_reason varchar(500),
        primary key (id)
    );

    create table commerce_store (
        active boolean not null,
        brand_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        business_type varchar(30) not null check (business_type in ('FOOD_SERVICE','ONLINE_RETAIL')),
        store_code varchar(40) not null,
        brand_name varchar(100) not null,
        store_name varchar(100) not null,
        description varchar(200) not null,
        primary key (id),
        constraint uk_commerce_store_code unique (store_code)
    );

    create table external_send_history (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        send_request_id bigint not null,
        sent_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        result_status varchar(30) not null,
        target_system varchar(40) not null,
        result_message varchar(200),
        request_body text,
        response_body text,
        primary key (id)
    );

    create table external_send_request (
        max_retry_count integer not null,
        retry_count integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_sent_at timestamp(6),
        processing_started_at timestamp(6),
        sales_id bigint not null,
        updated_at timestamp(6) not null,
        send_status varchar(30) not null check (send_status in ('READY','SENDING','SUCCESS','FAILED')),
        target_system varchar(40) not null,
        request_key varchar(100) not null,
        last_error_message varchar(200),
        primary key (id),
        constraint uk_external_send_request_key unique (request_key)
    );

    create table inventory_lot (
        available_quantity integer not null,
        expiration_date date,
        manufactured_date date,
        received_quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        store_id bigint not null,
        updated_at timestamp(6) not null,
        variant_id bigint not null,
        lot_no varchar(80) not null,
        memo varchar(200),
        primary key (id),
        constraint uk_inventory_lot_store_variant_lot unique (store_id, variant_id, lot_no)
    );

    create table inventory_transaction (
        quantity integer not null,
        reserved_after integer not null,
        reserved_before integer not null,
        stock_after integer not null,
        stock_before integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        reference_id bigint,
        updated_at timestamp(6) not null,
        variant_id bigint not null,
        type varchar(20) not null check (type in ('RECEIPT','RESERVE','RELEASE','SHIPMENT','ADJUST_IN','ADJUST_OUT','TRANSFER_OUT','TRANSFER_IN')),
        actor varchar(40),
        reference_type varchar(40),
        sku varchar(100) not null,
        reason varchar(200),
        primary key (id)
    );

    create table journal_entry (
        entry_date date not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        source_id bigint not null,
        store_id bigint,
        updated_at timestamp(6) not null,
        source_type varchar(30) not null,
        source_ref varchar(120),
        description varchar(200) not null,
        primary key (id),
        constraint uk_journal_entry_source unique (source_type, source_id)
    );

    create table journal_line (
        credit numeric(19,2) not null,
        debit numeric(19,2) not null,
        line_no integer not null,
        id bigint generated by default as identity,
        journal_entry_id bigint not null,
        store_id bigint,
        account_code varchar(10) not null,
        account_name varchar(60) not null,
        primary key (id)
    );

    create table option_group_template (
        max_selection integer not null,
        min_selection integer not null,
        required_option boolean not null,
        sort_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        selection_type varchar(20) not null check (selection_type in ('SINGLE','MULTIPLE')),
        customer_display_name varchar(100),
        template_name varchar(100) not null,
        primary key (id)
    );

    create table option_value_template (
        default_additional_price numeric(19,2) not null,
        sort_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        template_group_id bigint not null,
        updated_at timestamp(6) not null,
        value_name varchar(100) not null,
        primary key (id)
    );

    create table payment_auth_session (
        amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        expired_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        currency varchar(10) not null,
        status varchar(30) not null check (status in ('REQUEST_READY','AUTH_RESULT_RECEIVED','APPROVED','FAILED')),
        mid varchar(40) not null,
        auth_token varchar(80) not null,
        order_no varchar(80) not null,
        approved_tid varchar(120),
        buyer_name varchar(120) not null,
        product_name varchar(120) not null,
        primary key (id),
        constraint uk_payment_auth_session_order_no unique (order_no),
        constraint uk_payment_auth_session_auth_token unique (auth_token)
    );

    create table payment_cancel (
        cancel_amount numeric(19,2) not null,
        canceled_at timestamp(6) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        payment_id bigint not null,
        updated_at timestamp(6) not null,
        cancel_status varchar(30) not null check (cancel_status in ('CANCEL_REQUESTED','SUCCESS','FAILED','CANCEL_UNKNOWN','CANCEL_RECONCILE_REQUIRED')),
        cancel_type varchar(30) not null check (cancel_type in ('FULL','PARTIAL')),
        cancel_request_key varchar(100) not null,
        tid varchar(120) not null,
        cancel_reason varchar(200),
        primary key (id),
        constraint uk_payment_cancel_request_key unique (cancel_request_key)
    );

    create table payment_recovery_task (
        max_retry_count integer not null,
        retry_count integer not null,
        cancel_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_tried_at timestamp(6),
        payment_id bigint,
        processed_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(30) not null check (status in ('READY','PROCESSING','SUCCESS','FAILED')),
        recovery_type varchar(40) not null check (recovery_type in ('APPROVE_UNKNOWN_CHECK','NETWORK_CANCEL','APPROVE_INTERNAL_SAVE_FAILED','CANCEL_UNKNOWN_CHECK','EXTERNAL_SEND_RETRY','ALIMTALK_RETRY')),
        order_no varchar(80),
        idempotency_key varchar(120),
        tid varchar(120),
        task_key varchar(160) not null,
        last_error_message varchar(300),
        primary key (id),
        constraint uk_payment_recovery_task_key unique (task_key)
    );

    create table payment_transaction (
        approved_amount numeric(19,2) not null,
        canceled_amount numeric(19,2) not null,
        approved_at timestamp(6) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        store_id bigint,
        updated_at timestamp(6) not null,
        version bigint,
        currency varchar(10) not null,
        payment_status varchar(30) not null check (payment_status in ('READY','APPROVE_REQUESTED','APPROVED','APPROVE_FAILED','APPROVE_UNKNOWN','CANCEL_REQUESTED','PARTIAL_CANCELED','CANCELED','CANCEL_FAILED','CANCEL_UNKNOWN','CANCEL_RECONCILE_REQUIRED','NETWORK_CANCEL_REQUIRED','NETWORK_CANCEL_SUCCESS','NETWORK_CANCEL_FAILED','UNKNOWN')),
        mid varchar(40) not null,
        pg_provider varchar(40) not null check (pg_provider in ('MOCK','INICIS')),
        order_no varchar(80) not null,
        approval_request_key varchar(120),
        tid varchar(120) not null,
        failure_reason varchar(200),
        product_name varchar(200),
        primary key (id),
        constraint uk_payment_transaction_order_no unique (order_no),
        constraint uk_payment_transaction_tid unique (tid),
        constraint uk_payment_transaction_approval_key unique (approval_request_key)
    );

    create table pg_api_log (
        http_status integer,
        success_yn boolean,
        created_at timestamp(6) not null,
        duration_ms bigint,
        id bigint generated by default as identity,
        logged_at timestamp(6) not null,
        payment_id bigint,
        updated_at timestamp(6) not null,
        result_status varchar(30) not null check (result_status in ('READY','RECEIVED','REQUESTED','SUCCESS','FAILED','NET_CANCEL_REQUESTED')),
        api_type varchar(40) not null check (api_type in ('STD_PAY_READY','AUTH_RESULT','APPROVE','CANCEL','NETWORK_CANCEL','INQUIRY','NET_CANCEL')),
        event_type varchar(40) check (event_type in ('APPROVE','CANCEL','QUERY','CALLBACK')),
        pg_company varchar(40) not null check (pg_company in ('INICIS','STRIPE','PAYMENTWALL')),
        pg_provider varchar(40) check (pg_provider in ('MOCK','INICIS')),
        order_no varchar(80),
        request_id varchar(100),
        idempotency_key varchar(120),
        tid varchar(120),
        result_message varchar(200),
        error_message varchar(300),
        request_body text,
        response_body text,
        primary key (id)
    );

    create table pg_fee_policy (
        effective_end_date date not null,
        effective_start_date date not null,
        fee_rate numeric(10,4) not null,
        use_yn boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        mid varchar(40) not null,
        payment_method varchar(40) not null,
        pg_company varchar(40) not null,
        primary key (id)
    );

    create table pg_settlement_import (
        business_date date not null,
        matched_count integer not null,
        mismatch_count integer not null,
        total_count integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        pg_company varchar(40) not null,
        status varchar(40) not null,
        mid varchar(80) not null,
        file_name varchar(120) not null,
        primary key (id)
    );

    create table pg_settlement_reconciliation (
        internal_amount numeric(19,2),
        pg_amount numeric(19,2),
        pg_fee numeric(19,2),
        id bigint generated by default as identity,
        import_id bigint not null,
        resolved_at timestamp(6),
        sales_transaction_id bigint,
        resolution_status varchar(20) not null check (resolution_status in ('NOT_REQUIRED','OPEN','IN_REVIEW','RESOLVED','EXCLUDED')),
        status varchar(30) not null check (status in ('MATCHED','INTERNAL_ONLY','PG_ONLY','AMOUNT_MISMATCH','FEE_MISMATCH')),
        assignee varchar(80),
        order_no varchar(100),
        tid varchar(120),
        reason varchar(300),
        resolution_note varchar(500),
        primary key (id)
    );

    create table product (
        inventory_managed boolean not null,
        sale_price numeric(19,2) not null,
        stock_quantity integer not null,
        brand_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint,
        sale_status varchar(30) not null check (sale_status in ('ON_SALE','SOLD_OUT','STOPPED')),
        store_code varchar(40),
        product_code varchar(80) not null,
        category varchar(100),
        product_name varchar(200) not null,
        image_url varchar(500),
        primary key (id),
        constraint uk_product_store_code unique (store_code, product_code)
    );

    create table product_addon_group (
        exposed boolean not null,
        max_quantity integer not null,
        min_quantity integer not null,
        sort_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        group_name varchar(100) not null,
        primary key (id)
    );

    create table product_addon_item (
        max_quantity integer not null,
        sort_order integer not null,
        addon_group_id bigint not null,
        addon_product_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        primary key (id),
        constraint uk_addon_group_product unique (addon_group_id, addon_product_id)
    );

    create table product_category (
        exposed boolean not null,
        sort_order integer not null,
        brand_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        store_code varchar(40),
        category_name varchar(100) not null,
        primary key (id),
        constraint uk_product_category_store_name unique (store_code, category_name)
    );

    create table product_option_group (
        exposed boolean not null,
        max_selection integer not null,
        min_selection integer not null,
        required_option boolean not null,
        sort_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        selection_type varchar(20) not null check (selection_type in ('SINGLE','MULTIPLE')),
        group_name varchar(100) not null,
        primary key (id)
    );

    create table product_option_value (
        additional_price numeric(19,2) not null,
        inventory_managed boolean not null,
        sort_order integer not null,
        stock_quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        option_group_id bigint not null,
        updated_at timestamp(6) not null,
        sale_status varchar(30) not null check (sale_status in ('ON_SALE','SOLD_OUT','STOPPED')),
        value_name varchar(100) not null,
        primary key (id)
    );

    create table product_variant (
        additional_price numeric(19,2) not null,
        reserved_quantity integer not null,
        safety_stock integer not null,
        sort_order integer not null,
        stock_quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6) not null,
        sale_status varchar(30) not null check (sale_status in ('ON_SALE','SOLD_OUT','STOPPED')),
        barcode varchar(64),
        sku varchar(100) not null,
        combination_key varchar(500) not null,
        option_summary varchar(500) not null,
        primary key (id),
        constraint uk_product_variant_sku unique (sku),
        constraint uk_product_variant_combination unique (product_id, combination_key),
        constraint uk_product_variant_barcode unique (barcode)
    );

    create table purchase_order (
        expected_arrival_date date,
        total_amount numeric(19,2) default 0 not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        ordered_at timestamp(6),
        store_id bigint not null,
        supplier_id bigint not null,
        updated_at timestamp(6) not null,
        status varchar(24) not null check (status in ('DRAFT','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELED')),
        actor varchar(40),
        po_no varchar(40) not null,
        memo varchar(300),
        primary key (id),
        constraint uk_purchase_order_no unique (po_no)
    );

    create table purchase_order_item (
        ordered_quantity integer not null,
        received_quantity integer default 0 not null,
        unit_cost numeric(19,2) not null,
        id bigint generated by default as identity,
        purchase_order_id bigint not null,
        variant_id bigint not null,
        primary key (id)
    );

    create table sales_transaction (
        business_date date not null,
        confirmed_yn boolean not null,
        external_send_required boolean not null,
        sale_amount numeric(19,2) not null,
        settlement_included_yn boolean not null,
        supply_amount numeric(19,2) not null,
        total_amount numeric(19,2) not null,
        vat_amount numeric(19,2) not null,
        cancel_id bigint,
        confirmed_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        order_item_id bigint,
        original_sales_transaction_id bigint,
        payment_id bigint,
        seller_id bigint,
        source_id bigint not null,
        store_id bigint,
        updated_at timestamp(6) not null,
        sale_type varchar(20) not null check (sale_type in ('SALE','CANCEL','ADJUST')),
        source_type varchar(20) not null,
        ledger_status varchar(30) not null check (ledger_status in ('POSTED','EXCLUDED','ERROR','ADJUSTED','CANCELED')),
        sale_status varchar(30) not null check (sale_status in ('APPROVED','CANCELED','PARTIAL_CANCELED','SETTLEMENT_READY','SETTLED','SEND_FAILED','READY')),
        settlement_status varchar(30) not null check (settlement_status in ('NOT_SETTLED','SETTLEMENT_READY','CALCULATED','SETTLED','PAID','CARRIED_OVER','EXCLUDED')),
        payment_method varchar(40),
        pg_code varchar(40),
        order_no varchar(80) not null,
        pg_transaction_id varchar(120),
        tid varchar(120) not null,
        primary key (id),
        constraint uk_sales_transaction_source unique (source_type, source_id)
    );

    create table sales_transaction_line (
        business_date date not null,
        confirmed_yn boolean not null,
        line_amount numeric(19,2) not null,
        quantity integer not null,
        supply_amount numeric(19,2) not null,
        vat_amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        order_id bigint,
        order_item_id bigint,
        product_id bigint,
        sales_transaction_id bigint not null,
        store_id bigint,
        updated_at timestamp(6) not null,
        sale_type varchar(20) not null check (sale_type in ('SALE','CANCEL','ADJUST')),
        category_name varchar(100) not null,
        sku varchar(100),
        product_name varchar(200),
        primary key (id)
    );

    create table settlement_adjustment (
        adjustment_amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        sales_id bigint not null,
        updated_at timestamp(6) not null,
        adjustment_type varchar(30) not null,
        reason varchar(200) not null,
        primary key (id)
    );

    create table settlement_batch_log (
        failure_count integer not null,
        success_count integer not null,
        target_count integer not null,
        target_date date not null,
        created_at timestamp(6) not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        started_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        batch_status varchar(30) not null check (batch_status in ('RUNNING','SUCCESS','FAILED')),
        error_message varchar(200),
        primary key (id)
    );

    create table settlement_detail (
        fee_amount numeric(19,2) not null,
        net_amount numeric(19,2) not null,
        sale_amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        sales_id bigint not null,
        settlement_statement_id bigint not null,
        updated_at timestamp(6) not null,
        sale_type varchar(20) not null,
        primary key (id),
        constraint uk_settlement_detail_statement_sales unique (settlement_statement_id, sales_id)
    );

    create table settlement_fee_detail (
        fee_amount numeric(19,2) not null,
        fee_rate numeric(10,4) not null,
        vat_amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        fee_policy_id bigint not null,
        id bigint generated by default as identity,
        settlement_statement_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table settlement_log (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logged_at timestamp(6) not null,
        settlement_statement_id bigint not null,
        updated_at timestamp(6) not null,
        result_status varchar(30) not null,
        action_type varchar(40) not null,
        message varchar(200),
        primary key (id)
    );

    create table settlement_statement (
        adjustment_amount numeric(19,2) not null,
        fee_amount numeric(19,2) not null,
        gross_amount numeric(19,2) not null,
        hold_amount numeric(19,2) not null,
        net_amount numeric(19,2) not null,
        scheduled_payout_date date,
        settlement_date date not null,
        vat_amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        paid_at timestamp(6),
        store_id bigint,
        updated_at timestamp(6) not null,
        settlement_status varchar(30) not null check (settlement_status in ('DRAFT','CONFIRMED','PAID')),
        mid varchar(40) not null,
        pg_company varchar(40) not null,
        payout_account_masked varchar(80),
        payout_reference varchar(80),
        primary key (id),
        constraint uk_settlement_statement_date_mid_store unique (settlement_date, mid, store_id)
    );

    create table stock_count (
        completed_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        store_id bigint not null,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('IN_PROGRESS','COMPLETED','CANCELED')),
        actor varchar(40),
        count_no varchar(40) not null,
        memo varchar(300),
        primary key (id),
        constraint uk_stock_count_no unique (count_no)
    );

    create table stock_count_line (
        counted_quantity integer,
        difference_quantity integer default 0 not null,
        system_quantity integer not null,
        id bigint generated by default as identity,
        stock_count_id bigint not null,
        variant_id bigint not null,
        primary key (id),
        constraint uk_stock_count_line unique (stock_count_id, variant_id)
    );

    create table stock_transfer (
        created_at timestamp(6) not null,
        destination_store_id bigint not null,
        id bigint generated by default as identity,
        received_at timestamp(6),
        shipped_at timestamp(6),
        source_store_id bigint not null,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('REQUESTED','IN_TRANSIT','RECEIVED','CANCELLED')),
        actor varchar(60),
        transfer_no varchar(60) not null,
        reason varchar(200),
        primary key (id),
        constraint uk_stock_transfer_no unique (transfer_no)
    );

    create table stock_transfer_item (
        expiration_date date,
        quantity integer not null,
        unit_cost numeric(19,2) not null,
        id bigint generated by default as identity,
        transfer_id bigint not null,
        variant_id bigint not null,
        lot_no varchar(90),
        primary key (id)
    );

    create table store_product (
        exposed boolean not null,
        inventory_managed boolean not null,
        sale_price numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        store_id bigint not null,
        updated_at timestamp(6) not null,
        sale_status varchar(30) not null check (sale_status in ('ON_SALE','SOLD_OUT','STOPPED')),
        primary key (id),
        constraint uk_store_product unique (store_id, product_id)
    );

    create table store_variant_inventory (
        average_unit_cost numeric(19,2) not null,
        reserved_quantity integer not null,
        safety_stock integer default 0 not null,
        sale_enabled boolean not null,
        stock_quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        store_id bigint not null,
        updated_at timestamp(6) not null,
        variant_id bigint not null,
        primary key (id),
        constraint uk_store_variant_inventory unique (store_id, variant_id)
    );

    create table supplier (
        active boolean default true not null,
        lead_time_days integer default 14 not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        supplier_code varchar(40) not null,
        contact varchar(60),
        manager_name varchar(60),
        name varchar(120) not null,
        memo varchar(300),
        primary key (id),
        constraint uk_supplier_code unique (supplier_code)
    );

    create index idx_journal_line_entry 
       on journal_line (journal_entry_id);

    create index idx_journal_line_account 
       on journal_line (account_code);

    create index idx_journal_line_store_account 
       on journal_line (store_id, account_code);

    create index idx_sales_line_header 
       on sales_transaction_line (sales_transaction_id);

    create index idx_sales_line_category 
       on sales_transaction_line (business_date, category_name);

    create index idx_sales_line_product 
       on sales_transaction_line (product_id);

    alter table if exists admin_navigation_item 
       add constraint FKkl0nps6530yboar9raav9smoj 
       foreign key (navigation_group_id) 
       references admin_navigation_group;
