create table pos_terminal (
    active boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_connected_at timestamp(6),
    store_id bigint not null,
    updated_at timestamp(6) not null,
    app_version varchar(30),
    terminal_code varchar(40) not null,
    credential_hash varchar(100) not null,
    terminal_name varchar(100) not null,
    primary key (id),
    constraint uk_pos_terminal_store_code unique (store_id, terminal_code)
);

create index idx_pos_terminal_store_active on pos_terminal (store_id, active);

create table pos_inbound_request (
    retry_count integer not null,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    store_id bigint not null,
    terminal_id bigint not null,
    updated_at timestamp(6) not null,
    request_type varchar(30) not null,
    status varchar(30) not null,
    request_hash varchar(64) not null,
    error_code varchar(60),
    client_request_id varchar(80) not null,
    server_reference varchar(80),
    error_message varchar(500),
    primary key (id),
    constraint uk_pos_request_terminal_client unique (terminal_id, client_request_id),
    constraint fk_pos_request_terminal foreign key (terminal_id) references pos_terminal (id)
);

create index idx_pos_request_status_created on pos_inbound_request (status, created_at);
create index idx_pos_request_store_created on pos_inbound_request (store_id, created_at);
