create table pos_sync_execution (
    success_count integer not null,
    failure_count integer not null,
    retry_count integer not null,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    reported_at timestamp(6) not null,
    store_id bigint not null,
    terminal_id bigint not null,
    updated_at timestamp(6) not null,
    resource_type varchar(30) not null,
    status varchar(30) not null,
    error_code varchar(60),
    client_run_id varchar(80) not null,
    cursor_value varchar(200),
    error_message varchar(500),
    primary key (id),
    constraint uk_pos_sync_terminal_run unique (terminal_id, client_run_id),
    constraint fk_pos_sync_terminal foreign key (terminal_id) references pos_terminal (id)
);

create index idx_pos_sync_terminal_resource_status on pos_sync_execution (terminal_id, resource_type, status, completed_at);
create index idx_pos_sync_terminal_status_reported on pos_sync_execution (terminal_id, status, reported_at);
