alter table pos_terminal add column sync_interval_seconds integer not null default 300;
alter table pos_terminal add column request_timeout_seconds integer not null default 30;
alter table pos_terminal add column max_retry_count integer not null default 5;
alter table pos_terminal add column log_retention_days integer not null default 30;

create table pos_client_log (
    retried boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    retried_at timestamp(6),
    store_id bigint not null,
    terminal_id bigint not null,
    updated_at timestamp(6) not null,
    log_level varchar(10) not null,
    category varchar(20) not null,
    request_id varchar(80),
    error_message varchar(500) not null,
    stack_trace varchar(4000),
    primary key (id),
    constraint fk_pos_log_terminal foreign key (terminal_id) references pos_terminal (id)
);
create index idx_pos_log_terminal_occurred on pos_client_log (terminal_id, occurred_at);
create index idx_pos_log_level_category on pos_client_log (log_level, category);
